SET ECHO OFF
SET VERIFY OFF
SET SERVEROUTPUT ON
SET DEFINE ON
WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ACCEPT MGMT_DB_PASSWORD CHAR PROMPT 'MP_MGMT password: ' HIDE
ACCEPT APP2_DB_PASSWORD CHAR PROMPT 'MP_APP2 password: ' HIDE
DECLARE
 PROCEDURE ensure_user(u VARCHAR2,p VARCHAR2) IS n NUMBER;
 BEGIN
  IF NOT REGEXP_LIKE(p,'^[A-Za-z0-9]{24,64}$','c') THEN RAISE_APPLICATION_ERROR(-20001,'Invalid password'); END IF;
  SELECT COUNT(*) INTO n FROM all_users WHERE username=u;
  IF n=0 THEN EXECUTE IMMEDIATE 'CREATE USER '||u||' IDENTIFIED BY "'||p||'" DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS'; END IF;
  EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER, CREATE VIEW, CREATE PROCEDURE TO '||u;
  DBMS_OUTPUT.PUT_LINE(u||': ready (existing password unchanged)');
 END;
BEGIN
 ensure_user('MP_MGMT','&MGMT_DB_PASSWORD');
 ensure_user('MP_APP2','&APP2_DB_PASSWORD');
END;
/
UNDEFINE MGMT_DB_PASSWORD
UNDEFINE APP2_DB_PASSWORD
