apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager
  namespace: observability
data:
  alertmanager.yml: |
    route:
      receiver: lab
      group_by:
      - alertname
      - instance
      group_wait: 30s
    receivers:
    - name: lab
