apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: internal-b
  namespace: gateway
spec:
  vpcID: '@@VPC_ID@@'
  targetGroupARN: '@@TG_INTERNAL_B@@'
  targetType: ip
  serviceRef:
    name: gateway-b
    port: 8080
