apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: internal-a
  namespace: gateway
spec:
  vpcID: '@@VPC_ID@@'
  targetGroupARN: '@@TG_INTERNAL_A@@'
  targetType: ip
  serviceRef:
    name: gateway-a
    port: 8080
