input { beats { port => 5044 } }
filter {
 if [message] { mutate { add_field => { "platform_ingest" => "filebeat" } } }
}
output {
 elasticsearch {
  hosts => ["${ELASTICSEARCH_URL}"]
  index => "platform-%{+YYYY.MM.dd}"
  ilm_enabled => false
 }
}
