apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-b
  namespace: observability
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: filestream
      id: containers-b
      prospector.scanner.symlinks: true
      paths:
      - /var/log/containers/*.log
      parsers:
      - container:
          stream: all
          format: auto
      prospector.scanner.exclude_files:
      - filebeat-
    output.logstash:
      hosts:
      - logstash-b.observability.svc:5044
    queue.disk:
      max_size: 1GB
    processors:
    - add_fields:
        target: platform
        fields:
          source_id: ${SOURCE_NODE}
