apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: observability
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    rule_files:
    - /rules/*.yml
    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - alertmanager-a.observability.svc:9093
          - alertmanager-b.observability.svc:9093
    scrape_configs:
    - job_name: jvm
      metrics_path: /actuator/prometheus
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels:
        - __meta_kubernetes_pod_label_app
        regex: management|gateway|app1|routing
        action: keep
      - source_labels:
        - __meta_kubernetes_pod_container_port_number
        regex: '8080'
        action: keep
      - source_labels:
        - __meta_kubernetes_pod_label_site
        target_label: site
    - job_name: app2
      metrics_path: /actuator/prometheus
      static_configs:
      - targets:
        - '@@APP2_A_IP@@:8080'
        labels:
          site: a
      - targets:
        - '@@APP2_B_IP@@:8080'
        labels:
          site: b
    - job_name: rhel-nodes
      static_configs:
      - targets:
        - '@@APP2_A_IP@@:9100'
        labels:
          site: a
      - targets:
        - '@@APP2_B_IP@@:9100'
        labels:
          site: b
