apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-data-a
  namespace: observability
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: platform-gp3
  resources:
    requests:
      storage: 10Gi
