apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: logs-b
  namespace: observability
spec:
  vpcID: '@@VPC_ID@@'
  targetGroupARN: '@@DISC_B_LOGSTASH@@'
  targetType: ip
  serviceRef:
    name: logstash-b
    port: 5044
