DECLARE
v_count NUMBER;
BEGIN
SELECT COUNT(*) INTO v_count FROM all_users WHERE username = 'MP_MGMT';
IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER MP_MGMT IDENTIFIED BY "&MGMT_DB_PASSWORD" DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS';
END IF;

SELECT COUNT(*) INTO v_count FROM all_users WHERE username = 'MP_GRDC';
IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER MP_GRDC IDENTIFIED BY "&GRDC_DB_PASSWORD" DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS';
END IF;
END;
/

GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER TO MP_MGMT;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER TO MP_GRDC;
